baseURL = 'https://guides.dalton.dog/'
languageCode = 'en-us'
title = "Dalton's Game Guides"
copyright = "Dalton Williams 2025"

[params]
	subtitle = "Checklists and Tables and Such"
	[params.contact]
		email = "email@dalton.dog"
	
