baseURL: https://guides.dalton.dog/
languageCode: en-us
title: Game Guides
copyright: Dalton Williams 2025

caches:
  images:
    dir: :cacheDir/images

params:
  author: Dalton Williams
  subtitle: Checklists and Tables and Such
